PRAGMA foreign_keys = ON;
BEGIN TRANSACTION;
-- Seed control families
INSERT OR IGNORE INTO control_families (code, name, description) VALUES ('AC', 'Access Control', 'Official CMMC Level 2 control family AC');
INSERT OR IGNORE INTO control_families (code, name, description) VALUES ('AT', 'Awareness and Training', 'Official CMMC Level 2 control family AT');
INSERT OR IGNORE INTO control_families (code, name, description) VALUES ('AU', 'Audit and Accountability', 'Official CMMC Level 2 control family AU');
INSERT OR IGNORE INTO control_families (code, name, description) VALUES ('CA', 'Assessment, Authorization, and Monitoring', 'Official CMMC Level 2 control family CA');
INSERT OR IGNORE INTO control_families (code, name, description) VALUES ('CM', 'Configuration Management', 'Official CMMC Level 2 control family CM');
INSERT OR IGNORE INTO control_families (code, name, description) VALUES ('IA', 'Identification and Authentication', 'Official CMMC Level 2 control family IA');
INSERT OR IGNORE INTO control_families (code, name, description) VALUES ('IR', 'Incident Response', 'Official CMMC Level 2 control family IR');
INSERT OR IGNORE INTO control_families (code, name, description) VALUES ('MA', 'Maintenance', 'Official CMMC Level 2 control family MA');
INSERT OR IGNORE INTO control_families (code, name, description) VALUES ('MP', 'Media Protection', 'Official CMMC Level 2 control family MP');
INSERT OR IGNORE INTO control_families (code, name, description) VALUES ('PE', 'Physical Protection', 'Official CMMC Level 2 control family PE');
INSERT OR IGNORE INTO control_families (code, name, description) VALUES ('PS', 'Personnel Security', 'Official CMMC Level 2 control family PS');
INSERT OR IGNORE INTO control_families (code, name, description) VALUES ('RA', 'Risk Assessment', 'Official CMMC Level 2 control family RA');
INSERT OR IGNORE INTO control_families (code, name, description) VALUES ('SC', 'System and Communications Protection', 'Official CMMC Level 2 control family SC');
INSERT OR IGNORE INTO control_families (code, name, description) VALUES ('SI', 'System and Information Integrity', 'Official CMMC Level 2 control family SI');

-- Seed controls from CMMC-L2.xlsx
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.1.1', cf.id, 'Limit system access to authorized users and processes' FROM control_families cf WHERE cf.code = 'AC';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.1.10', cf.id, 'Use session lock with pattern-hiding displays' FROM control_families cf WHERE cf.code = 'AC';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.1.11', cf.id, 'Terminate user session after defined condition' FROM control_families cf WHERE cf.code = 'AC';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.1.12', cf.id, 'Monitor and control remote access sessions' FROM control_families cf WHERE cf.code = 'AC';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.1.13', cf.id, 'Employ cryptographic mechanisms to protect remote access' FROM control_families cf WHERE cf.code = 'AC';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.1.14', cf.id, 'Route remote access via managed access control points' FROM control_families cf WHERE cf.code = 'AC';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.1.15', cf.id, 'Authorize remote execution of privileged commands' FROM control_families cf WHERE cf.code = 'AC';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.1.16', cf.id, 'Authorize wireless access prior to allowing connections' FROM control_families cf WHERE cf.code = 'AC';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.1.17', cf.id, 'Protect wireless access using authentication and encryption' FROM control_families cf WHERE cf.code = 'AC';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.1.18', cf.id, 'Control connection of mobile devices' FROM control_families cf WHERE cf.code = 'AC';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.1.19', cf.id, 'Encrypt CUI on mobile devices and mobile platforms' FROM control_families cf WHERE cf.code = 'AC';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.1.2', cf.id, 'Limit system access to authorized transaction types/functions' FROM control_families cf WHERE cf.code = 'AC';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.1.20', cf.id, 'Verify and control connections to external systems' FROM control_families cf WHERE cf.code = 'AC';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.1.21', cf.id, 'Limit use of portable storage on external systems' FROM control_families cf WHERE cf.code = 'AC';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.1.22', cf.id, 'Control CUI posted on publicly accessible systems' FROM control_families cf WHERE cf.code = 'AC';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.1.3', cf.id, 'Control flow of CUI per approved authorizations' FROM control_families cf WHERE cf.code = 'AC';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.1.4', cf.id, 'Separate duties of individuals to reduce collusion risk' FROM control_families cf WHERE cf.code = 'AC';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.1.5', cf.id, 'Employ least privilege including privileged accounts' FROM control_families cf WHERE cf.code = 'AC';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.1.6', cf.id, 'Use non-privileged accounts for non-security functions' FROM control_families cf WHERE cf.code = 'AC';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.1.7', cf.id, 'Prevent non-privileged users from executing privileged functions' FROM control_families cf WHERE cf.code = 'AC';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.1.8', cf.id, 'Limit unsuccessful logon attempts' FROM control_families cf WHERE cf.code = 'AC';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.1.9', cf.id, 'Provide privacy and security notices consistent with CUI rules' FROM control_families cf WHERE cf.code = 'AC';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.2.1', cf.id, 'Train managers/users on security risks and policies' FROM control_families cf WHERE cf.code = 'AT';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.2.2', cf.id, 'Train personnel on their assigned security duties' FROM control_families cf WHERE cf.code = 'AT';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.2.3', cf.id, 'Provide insider threat awareness training' FROM control_families cf WHERE cf.code = 'AT';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.3.1', cf.id, 'Create and retain system audit records to support monitoring' FROM control_families cf WHERE cf.code = 'AU';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.3.2', cf.id, 'Ensure user actions can be uniquely traced for accountability' FROM control_families cf WHERE cf.code = 'AU';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.3.3', cf.id, 'Review and update logged event types' FROM control_families cf WHERE cf.code = 'AU';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.3.4', cf.id, 'Alert on audit logging process failures' FROM control_families cf WHERE cf.code = 'AU';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.3.5', cf.id, 'Correlate audit record review, analysis, and reporting' FROM control_families cf WHERE cf.code = 'AU';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.3.6', cf.id, 'Provide audit record reduction and report generation' FROM control_families cf WHERE cf.code = 'AU';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.3.7', cf.id, 'Use authoritative time source for audit record timestamps' FROM control_families cf WHERE cf.code = 'AU';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.3.8', cf.id, 'Protect audit information and audit tools from tampering' FROM control_families cf WHERE cf.code = 'AU';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.3.9', cf.id, 'Limit management of audit logging to privileged users' FROM control_families cf WHERE cf.code = 'AU';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.12.1', cf.id, 'Periodically assess security controls for effectiveness' FROM control_families cf WHERE cf.code = 'CA';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.12.2', cf.id, 'Develop and implement POA&Ms to reduce known weaknesses' FROM control_families cf WHERE cf.code = 'CA';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.12.3', cf.id, 'Monitor security controls on an ongoing basis' FROM control_families cf WHERE cf.code = 'CA';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.12.4', cf.id, 'Develop, document, and periodically update System Security Plan' FROM control_families cf WHERE cf.code = 'CA';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.4.1', cf.id, 'Establish and maintain baseline configurations and inventories' FROM control_families cf WHERE cf.code = 'CM';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.4.2', cf.id, 'Establish and enforce security configuration settings' FROM control_families cf WHERE cf.code = 'CM';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.4.3', cf.id, 'Track, review, approve, log configuration changes' FROM control_families cf WHERE cf.code = 'CM';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.4.4', cf.id, 'Analyze security impact of changes before implementation' FROM control_families cf WHERE cf.code = 'CM';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.4.5', cf.id, 'Define/document/approve access restrictions for changes' FROM control_families cf WHERE cf.code = 'CM';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.4.6', cf.id, 'Employ principle of least functionality on systems' FROM control_families cf WHERE cf.code = 'CM';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.4.7', cf.id, 'Restrict/disable/prevent nonessential programs and services' FROM control_families cf WHERE cf.code = 'CM';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.4.8', cf.id, 'Apply deny-by-exception or permit-by-exception software policy' FROM control_families cf WHERE cf.code = 'CM';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.4.9', cf.id, 'Control and monitor user-installed software' FROM control_families cf WHERE cf.code = 'CM';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.5.1', cf.id, 'Identify system users, processes, and devices' FROM control_families cf WHERE cf.code = 'IA';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.5.10', cf.id, 'Store and transmit only cryptographically protected passwords' FROM control_families cf WHERE cf.code = 'IA';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.5.11', cf.id, 'Obscure feedback of authentication information' FROM control_families cf WHERE cf.code = 'IA';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.5.2', cf.id, 'Authenticate identities of users, processes, or devices' FROM control_families cf WHERE cf.code = 'IA';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.5.3', cf.id, 'Use multifactor authentication for privileged and network access' FROM control_families cf WHERE cf.code = 'IA';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.5.4', cf.id, 'Employ replay-resistant authentication for accounts' FROM control_families cf WHERE cf.code = 'IA';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.5.5', cf.id, 'Prevent reuse of identifiers for a defined period' FROM control_families cf WHERE cf.code = 'IA';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.5.6', cf.id, 'Disable identifiers after defined inactivity period' FROM control_families cf WHERE cf.code = 'IA';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.5.7', cf.id, 'Enforce minimum password complexity and change on creation' FROM control_families cf WHERE cf.code = 'IA';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.5.8', cf.id, 'Prohibit password reuse for a specified number of generations' FROM control_families cf WHERE cf.code = 'IA';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.5.9', cf.id, 'Allow temporary passwords only with immediate change' FROM control_families cf WHERE cf.code = 'IA';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.6.1', cf.id, 'Establish operational incident-handling capability' FROM control_families cf WHERE cf.code = 'IR';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.6.2', cf.id, 'Track, document, and report incidents to designated parties' FROM control_families cf WHERE cf.code = 'IR';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.6.3', cf.id, 'Test organizational incident response capability' FROM control_families cf WHERE cf.code = 'IR';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.7.1', cf.id, 'Perform maintenance on organizational systems' FROM control_families cf WHERE cf.code = 'MA';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.7.2', cf.id, 'Control tools, techniques, mechanisms used for maintenance' FROM control_families cf WHERE cf.code = 'MA';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.7.3', cf.id, 'Ensure equipment sanitized of CUI before off-site maintenance' FROM control_families cf WHERE cf.code = 'MA';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.7.4', cf.id, 'Check diagnostic/test media for malicious code' FROM control_families cf WHERE cf.code = 'MA';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.7.5', cf.id, 'Require MFA for remote/nonlocal maintenance sessions' FROM control_families cf WHERE cf.code = 'MA';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.7.6', cf.id, 'Supervise maintenance activities by non-cleared personnel' FROM control_families cf WHERE cf.code = 'MA';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.8.1', cf.id, 'Protect system media containing CUI (paper and digital)' FROM control_families cf WHERE cf.code = 'MP';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.8.2', cf.id, 'Limit access to CUI on media to authorized users' FROM control_families cf WHERE cf.code = 'MP';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.8.3', cf.id, 'Sanitize or destroy media before disposal or reuse' FROM control_families cf WHERE cf.code = 'MP';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.8.4', cf.id, 'Mark media with CUI markings and distribution limits' FROM control_families cf WHERE cf.code = 'MP';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.8.5', cf.id, 'Control access to media and maintain accountability during transport' FROM control_families cf WHERE cf.code = 'MP';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.8.6', cf.id, 'Implement cryptographic protection of CUI on transported media' FROM control_families cf WHERE cf.code = 'MP';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.8.7', cf.id, 'Control use of removable media on system components' FROM control_families cf WHERE cf.code = 'MP';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.8.8', cf.id, 'Prohibit portable storage devices without identifiable owner' FROM control_families cf WHERE cf.code = 'MP';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.8.9', cf.id, 'Protect confidentiality of backup CUI at storage locations' FROM control_families cf WHERE cf.code = 'MP';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.10.1', cf.id, 'Limit physical access to systems, equipment, work environments' FROM control_families cf WHERE cf.code = 'PE';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.10.2', cf.id, 'Protect and monitor physical facility and support infrastructure' FROM control_families cf WHERE cf.code = 'PE';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.10.3', cf.id, 'Escort visitors and monitor visitor activity' FROM control_families cf WHERE cf.code = 'PE';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.10.4', cf.id, 'Maintain audit logs of physical access' FROM control_families cf WHERE cf.code = 'PE';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.10.5', cf.id, 'Control and manage physical access devices' FROM control_families cf WHERE cf.code = 'PE';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.10.6', cf.id, 'Enforce safeguarding measures for CUI at alternate work sites' FROM control_families cf WHERE cf.code = 'PE';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.9.1', cf.id, 'Screen individuals prior to authorizing access to CUI systems' FROM control_families cf WHERE cf.code = 'PS';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.9.2', cf.id, 'Ensure CUI/systems protected during/after personnel actions' FROM control_families cf WHERE cf.code = 'PS';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.11.1', cf.id, 'Periodically assess risk to operations and individuals' FROM control_families cf WHERE cf.code = 'RA';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.11.2', cf.id, 'Scan for vulnerabilities in systems and applications' FROM control_families cf WHERE cf.code = 'RA';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.11.3', cf.id, 'Remediate vulnerabilities per organizational risk assessments' FROM control_families cf WHERE cf.code = 'RA';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.13.1', cf.id, 'Monitor/control/protect communications at system boundaries' FROM control_families cf WHERE cf.code = 'SC';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.13.10', cf.id, 'Establish and manage cryptographic keys for cryptography' FROM control_families cf WHERE cf.code = 'SC';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.13.11', cf.id, 'Employ FIPS-validated cryptography to protect CUI' FROM control_families cf WHERE cf.code = 'SC';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.13.12', cf.id, 'Prohibit remote activation of collaborative computing devices' FROM control_families cf WHERE cf.code = 'SC';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.13.13', cf.id, 'Control and monitor use of mobile code' FROM control_families cf WHERE cf.code = 'SC';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.13.14', cf.id, 'Control and monitor use of VoIP technologies' FROM control_families cf WHERE cf.code = 'SC';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.13.15', cf.id, 'Protect authenticity of communications sessions' FROM control_families cf WHERE cf.code = 'SC';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.13.16', cf.id, 'Protect confidentiality of CUI at rest' FROM control_families cf WHERE cf.code = 'SC';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.13.2', cf.id, 'Employ architectural designs and security engineering principles' FROM control_families cf WHERE cf.code = 'SC';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.13.3', cf.id, 'Separate user functionality from system management functionality' FROM control_families cf WHERE cf.code = 'SC';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.13.4', cf.id, 'Prevent unauthorized and unintended information transfer' FROM control_families cf WHERE cf.code = 'SC';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.13.5', cf.id, 'Implement subnetworks for publicly accessible components' FROM control_families cf WHERE cf.code = 'SC';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.13.6', cf.id, 'Deny network communications by default, allow by exception' FROM control_families cf WHERE cf.code = 'SC';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.13.7', cf.id, 'Prevent remote devices from split tunneling' FROM control_families cf WHERE cf.code = 'SC';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.13.8', cf.id, 'Use cryptography to protect CUI during transmission' FROM control_families cf WHERE cf.code = 'SC';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.13.9', cf.id, 'Terminate network connections at end of session/inactivity' FROM control_families cf WHERE cf.code = 'SC';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.14.1', cf.id, 'Identify, report, and correct system flaws in a timely manner' FROM control_families cf WHERE cf.code = 'SI';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.14.2', cf.id, 'Provide malicious code protection at designated locations' FROM control_families cf WHERE cf.code = 'SI';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.14.3', cf.id, 'Monitor system security alerts and advisories and respond' FROM control_families cf WHERE cf.code = 'SI';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.14.4', cf.id, 'Update malicious code protection mechanisms when available' FROM control_families cf WHERE cf.code = 'SI';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.14.5', cf.id, 'Perform periodic/real-time scans of system and files' FROM control_families cf WHERE cf.code = 'SI';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.14.6', cf.id, 'Monitor organizational systems and network traffic' FROM control_families cf WHERE cf.code = 'SI';
INSERT OR IGNORE INTO controls (control_id, family_id, title) SELECT '3.14.7', cf.id, 'Identify unauthorized use of organizational systems' FROM control_families cf WHERE cf.code = 'SI';
COMMIT;
